spring:
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
  database:
    postgres:
      jdbcUrl: jdbc:postgresql://localhost:5432/sql_test_db
      username: postgres_db_user
      password: postgres_db_pw
      driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: nosql_test_db
      username: mongo_db_user
      password: mongo_db_pw
      authentication-database: admin